### ISSUE TITLE
Make sure consumer isn’t reused between PCs

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#100]
Also try to see if we can warn if a consumer already exists in the jam with the same consumer group.

**Comment by radoslawtwardy** [comment]
I don't understand this ticket, and i want to make sure: it will be possible to run several consumers in same consumer group (for horizontal scaling) normally as in "standard" kafka right ?

**Comment by astubbs** [comment]
Yes that's right. This is about preventing `Consumer` instances being reused within the same JVM.

**Comment by astubbs** [comment]
FYI the consumer framework itself will prevent this from happening, as a consumer can't be used by different threads. So this would be a nicer UX to fail fast, it won't actually be able to happen.
