### ISSUE TITLE
Integration with Kafka Connect

### ISSUE THREAD

**Issue by kondamudikarthik** [confluentinc/parallel-consumer#119]
This is more of a question, can we integrate parallel-consumer into KafkaConnect? Has anyone tried it? I believe we might need to change `pollConsumer` method in `WorkerSinkTask` to read messages in parallel. Is this something in your roadmap?  Thanks!

Hi @astubbs, do you have any thoughts on this?

**Comment by astubbs** [comment]
Hi! Yes, I've thought about this many times, and brought it up myself. I'm not aware of anyone trying it yet - but it seems like a very obvious marriage of performance :) But no, it's not planned to implement due to lack of demand.

**Comment by kondamudikarthik** [comment]
@astubbs Thanks for getting back, I'm willing to do this as we use connect a lot in our data pipelines. I will explore around on this and get back to you.

**Comment by astubbs** [comment]
Consider the inverse - teach PC to run connectors...

**Comment by johnbyrnejb** [comment]
Closing Issue
