### ISSUE TITLE
Ability use different consume and produce types for the key and value

### ISSUE THREAD

**Issue by BDeus** [confluentinc/parallel-consumer#175]
I don't think it's possible to use ParallelStreamProcessor with Consumer and Producer that do not share the same KeyType and ValueType.
Can this be considered in the future ?

**Comment by BDeus** [comment]
Hi,
i see that you remove the blocker label.
Do you think the 1.0 version won't break after the implementation of the fix ?

**Comment by astubbs** [comment]
> i see that you remove the blocker label.

Whoops - mistake :) Still plan on changing this. Will be resuming work on PC this week :)

**Comment by johnbyrnejb** [comment]
Closing Issue
