### ISSUE TITLE
Feature: Allow unordered processing of messages without a key in 'KEY' ordering mode

### ISSUE THREAD

**Issue by rjoly-qlik** [confluentinc/parallel-consumer#183]
In our use case, we have a vast majority of messages that are not order-dependent but we have a small pocket of messages that are.  Our intention was to use the NULL key for the messages that do not have an order requirement and use a proper key value on the few occasions where the order matters.  Rough guess is that 95% of our messages will use the NULL key.  In order to ensure that the keyed messages are processed in order, we have no choice but to use the KEY ordering method but this has the very adverse effect of essentially serializing the remaining 95% which negates the benefits of the PC.  This is because PC considers the NULL key as an actual key value and will process every message that share that NULL key in the order they appear in the partition.  

It would be nice if the PC offered an option (`nullKeysUnordered`?) that would make it process all un-keyed messages in parallel and only order the messages that do have a key.  

The issue was discussed with @astubbs in [this Slack thread](https://confluentcommunity.slack.com/archives/C499EFQS0/p1641503415014600).

**Comment by johnbyrnejb** [comment]
Closing Issue
