### ISSUE TITLE
Expose way to know if connection to Broker is lost then later regained

### ISSUE THREAD

**Issue by fowlerp-qlik** [confluentinc/parallel-consumer#185]
A client may have the need to expose its health to the rest of the system (Kubernetes) and so client needs a way to know if the parallel consumer connection to the broker has been lost. It later needs to be informed if the connection has been re-established. 

Related:
- #27 
- #345 
- #353

**Comment by astubbs** [comment]
@fowlerp-qlik are there mechanisms from the Kafka clients for this that you want exposed? Have you looked at available JMX metrics from the raw clients?

**Comment by astubbs** [comment]
@fowlerp-qlik do you specifically want to be informed of connection state changes, or is it enough to have the state exposed through metrics / health check?

**Comment by astubbs** [comment]
I've also just realised that AK consumer doesn't actually expose this either. We will be adding metrics very soon, let's see if that will be enough. Otherwise, we can also implement some active health check system like starting an admin client and interrogating the cluster about something.
