### ISSUE TITLE
Need ability to seek to the beginning of a partition

### ISSUE THREAD

**Issue by fowlerp-qlik** [confluentinc/parallel-consumer#191]
We need the option to read from the beginning of a partition. Something along the lines of https://stackoverflow.com/questions/49723182/kafka-consumer-seektobeginning but the parallel consumer does not expose seekToBeginning() or assignment(). Is it possible to expose these or provide an overall wrapper for seekToBeginning()?

Blocked by:
- #346

**Comment by astubbs** [comment]
This should be achievable from the following workaround: 
- shutdown PC
- use the raw consumer to seek the raw consumer 
- rebuild pc with the same consumer
- pc will start receiving records from wherever underlying consumer starts from

**Comment by rrva** [comment]
@astubbs  I can't figure out how to implement this workaround. Please provide a working example.

**Comment by astubbs** [comment]
You can try out the consumer interface branch now if you like - it works, and has been used in some experimental tests in other branches.

**Comment by johnbyrnejb** [comment]
Closing Issue
