### ISSUE TITLE
vert.x: Run user funtions in a Vertical instead of Java thread pool

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#205]
Currently a user's function can block the single worker thread that executes user functions. in the vert.x module, all user functions should be non-blocking. However, this is only by convention. 

By moving user function execution into a vert.x vertical, the worker thread cannot be blocked. Also this would be a closer model to the core module. We would also get the advantage of vertx's monitoring of thread execution.

The advantage of using a Vertical, instead of a normal thread pool is debatable, as there isn't much use for an Actor system in this part of the system.

**Comment by johnbyrnejb** [comment]
Closing Issue
