### ISSUE TITLE
Dynamic concurrency control with flow control or tcp congestion control theory

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#21]
Prevent user from having to choose a level of concurrency with either the core engine or the vertx engine. 

Uses concepts from tcp congestion control to set the thread pool size by measuring performance of execution.
Originally planned to do this by hand using concepts from Engineering Control Theory, but stumbled upon Netflix's concurrency-limits library, which uses very similar theory from TCP congestion control theory.

**Comment by johnbyrnejb** [comment]
Closing Issue
