### ISSUE TITLE
Add distributed rate limiting support 

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#24]
Use a central cache to share rate limit info amongst processing cluster, to implement coordination of rate limit exhaustion to prevent accidental overrun while effectively exhausting the available credits.

https://dzone.com/articles/introduction-jcache-jsr-107
https://github.com/vladimir-bukhtoyarov/bucket4j
vs
https://github.com/mokies/ratelimitj

resilience4j doesn't support distriubted rate limiting: https://github.com/resilience4j/resilience4j/issues/350#issuecomment-720961836

**Comment by johnbyrnejb** [comment]
Closing Issue
