### ISSUE TITLE
Retries handling

### ISSUE THREAD

**Issue by kartius** [confluentinc/parallel-consumer#248]
If parallel consumer got exception during the consuming event it try to process it again infinity amount. Could you suggest please, how can I handle retries and set a max limit?

**Comment by astubbs** [comment]
Sorry, I didn't see your report sooner. Thanks for contributing! 

Ah - yes, simply catch exceptions from your function, and do not throw any exception back up. I.e. "swallow" the exception. This will make PC think the processing has succeeded, and will continue. You can record the number of failed attempts somewhere in your code, or you can use the new `PollContext` object in the `master` branch which provides you with the failure count.

Also keep an eye on:
- #196 
- #65 
- #242 

See:
- #223
