### ISSUE TITLE
performance: Support asynchronous sending of result messages

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#29]
At the moment when using the consumer, process, produce loop - the produced messages are sent to the brokers synchronously. This is simpler, but sending asynchronously might be faster. If we want to commit offsets correctly though, we have to hold onto the work unit in a limbo state, until the async produce result has completed.

This would be easily added as another step in the state machine for a unit of work. However it may be tricky to handle producer send time outs, if too many messages are waiting to be sent with the producer, and the producer starts timing them out. In this case they could be retried easily, but back pressure must be put into the system to prevent further messages from being queued up which would exacerbate the problem.

**Comment by johnbyrnejb** [comment]
Closing Issue
