### ISSUE TITLE
Readme mentions this library is experimental. Is it still not stable to be used in production environments? 

### ISSUE THREAD

**Issue by vishmegh88** [confluentinc/parallel-consumer#292]
https://github.com/confluentinc/parallel-consumer#support-and-issues

Please clarify. We are considering to use parallel consumer for our use case but want to confirm what does experimental mean here. 
Is this something confluent will continue to support in future

**Comment by astubbs** [comment]
Hi @vishmegh88 ! Welcome to the projec! 

Yes, it can definitly be used in production and works very well.

It's been stable for prod for about a year now.

I am planning to remove / modify those labels once we cut #172 1.0. But the main difference between 1.0 and now is some small features - not stabilty. 
0.6 will contain a nice improvement / simplification to the architecture ( #270 ), but any stabilty issues are fixed quickly and there are none known to me currently.

Experimental is the old tag - i should remove that word. It's not experimental anymore. The main point i need to make atm is that you the project is not currently included in Confluent's support offerings, except trough consultation engagements.

Thank you for asking!

Let me know if there's anything else I can elaborate on.

**Comment by astubbs** [comment]
Please if you may, review https://github.com/confluentinc/parallel-consumer/pull/294 ?
