### ISSUE TITLE
batchSize(100) but only getting from 1 to 3 messages at a time in my callback method

### ISSUE THREAD

**Issue by mbieser** [confluentinc/parallel-consumer#373]
Is there some additional setting needed in order to get the requested batch size (100) ? My topic has some 10k messages and yet I can never seem to get a batch larger than size 3.

KafkaConsumer setup:
```
 Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "dev-hop-kafka1:9092");
        props.put(ConsumerConfig.GROUP_ID_CONFIG, UUID.randomUUID().toString());
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,
        KafkaAvroDeserializer.class.getName());
        props.put(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, "true");
        props.put(KafkaAvroDeserializerConfig.SCHEMA_REGISTRY_URL_CONFIG, "http://dev-hop-kafka1:8081");
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false); //Must be false when using Confluent's parallel consumer.
        this.consumer = new KafkaConsumer(props);
```

ParallelConsumer setup:

```
  var options = ParallelConsumerOptions.<String, String>builder()
        .ordering(KEY)
        .maxConcurrency(5)
        .batchSize(100)
        .consumer(consumer)
        .build();
        ParallelStreamProcessor<String, SpecificRecordBase> streamProcessor = ParallelStreamProcessor.createEosStreamProcessor(options);
        streamProcessor.subscribe(new ArrayList<>(List.of(topic)));
        
        streamProcessor.poll(context -> {
            
            Stream<RecordContext<String, SpecificRecordBase>> records = context.stream();
            
            out.println("received batch of size: " + records.collect(Collectors.toList()).size());
```

Output:
```
received batch of size: 1
received batch of size: 1
received batch of size: 1
received batch of size: 1
...
received batch of size: 2
received batch of size: 2
received batch of size: 2
---
received batch of size: 3
received batch of size: 3
received batch of size: 3
...
```

**Comment by mbieser** [comment]
It appears to grab the correct batch size only when  ```.ordering(UNORDERED)```  is used. 

Can you please confirm if this is the case?

**Comment by astubbs** [comment]
Yes, that's right - using KEY ordering it will only ever take one record for a given key, in an attempt to preserve KEY ordering even when using batches, so you would need a bigger key set.

What sort of behaviour are you looking for? I think we have a tracking issue to allow batches to have multiple records with the same key. Would you want /only/ records of the same key? or a mix when possible?

**Comment by mbieser** [comment]
> using KEY ordering it will only ever take one record for a given key, in an attempt to preserve KEY ordering even when using batches, so you would need a bigger key set.

I think this behavior should be documented, especially since KEY is the default ordering. 

We have several use cases, 
1) "Give me a batch of messages and we don't care about the order" --> Batching + ordering==UNORDERED works fine for this case.

2) "Give me a batch of messages and maintain PARTITION ordering". Don't mind if there are different keys included, but very much need large batches for effficient indexing (to elastic search). Must maintain ordering as they appeared in the partition. This does not currently work.

**Comment by doppelrittberger** [comment]
Hi,
we have the second use case as well: we want to process batches per partition but the current implementation just returns 1 message per partition. We process the batches with batch database statements and one-by-one processing is multitudes slower.
Any progress on this topic so far? I see other tickets are referring to this as well.
Thanks
