### ISSUE TITLE
pollAndProduce with input and output kafka topics having different content types

### ISSUE THREAD

**Issue by nareshv** [confluentinc/parallel-consumer#378]
Looks like the pollAndProduce() expects both input & output topics to have the same <K, V> type. We have input topic with payload as `byte[]` and output as an Confluent library encoded avro message. How to handle that ?

**Comment by astubbs** [comment]
Yes, that's right. It's a known gap, and is planned to be improved before 1.0 this year:
- #175 

See #175 for details, but the workaround is to use byte[] as your format, and do the serde yourself in your processing function. Sorry about that - it was an early oversight.

**Comment by astubbs** [comment]
Duplicates #175
