### ISSUE TITLE
parallel consumer not scaling as expected

### ISSUE THREAD

**Issue by pdeole** [confluentinc/parallel-consumer#397]
Hello Team, @astubbs 

I would first explain existing design, with regular consumer being used now:

Design#1:
No. of topics: 10 with 6 partitions each
Consumers: regular kafka consumers, 2 consumer threads per topic per pod. So total 20 consumers across 10 topic per pod
Consumer group: 3 pods in the consumer group, so total 60 consumer threads across 10 topics across 3 pods

Design #2:
I recently converted this to confluent parallel consumer. I used single parallel consumer consuming from 10 topics i.e. total 60 partitions and used maxConcurrency 25 per pod. So it will account to max concurrency 75 across 3 pods which is greater than 60 consumer threads in design #1. I was expecting that this would scale better than design #1 however as per testing carried out, this failed to support traffic that design #1 supported successfully i.e. it reported increasing consumer lag at the same traffic that design #1 did not report any lag on.

Can someone provide guidance if any configuration is missing, or how to enable logging or troubleshoot issues with the parallel consumer? 
OR should I try another configuration of 1 parallel consumer per subscription topic with lesser maxConcurrency e.g. 5 per parallel consumer? Is this more efficient configuration?

Here is pasting the configuration of parallel consumer:
```
   @Bean
   public ParallelReceiverMode measureProcessorParallelReceiverMode() {
       final Map<String, Object> consumerProperties = kafkaProperties.buildConsumerProperties();
       consumerProperties.put(JsonDeserializer.VALUE_DEFAULT_TYPE, MeasureInputEvent.class);
       LOG.debug("ApplicationConfig.measureProcessorConsumerFactory() : SessionTimeOut is [{}]", kafkaTuningConfig.getSessionTimeoutMs());
       LOG.debug("ApplicationConfig.measureProcessorConsumerFactory() : FetchMinBytes is [{}]", kafkaTuningConfig.getFetchMinBytes());
       LOG.debug("ApplicationConfig.measureProcessorConsumerFactory() : FetchMinBytes is [{}]", kafkaTuningConfig.getFetchMaxBytes());
       LOG.debug("ApplicationConfig.measureProcessorConsumerFactory() : MaxPartitionFetchBytes is [{}]", kafkaTuningConfig.getMaxPartitionFetchBytes());
       LOG.debug("ApplicationConfig.measureProcessorConsumerFactory() : FetchMaxWaitMs is [{}]", kafkaTuningConfig.getFetchMaxWaitMs());
       
       consumerProperties.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, String.valueOf(kafkaTuningConfig.getSessionTimeoutMs()));
       consumerProperties.put(ConsumerConfig.FETCH_MIN_BYTES_CONFIG, String.valueOf(kafkaTuningConfig.getFetchMinBytes()));
       consumerProperties.put(ConsumerConfig.FETCH_MAX_BYTES_CONFIG, String.valueOf(kafkaTuningConfig.getFetchMaxBytes()));
       consumerProperties.put(ConsumerConfig.MAX_PARTITION_FETCH_BYTES_CONFIG, String.valueOf(kafkaTuningConfig.getMaxPartitionFetchBytes()));
       consumerProperties.put(ConsumerConfig.FETCH_MAX_WAIT_MS_CONFIG, String.valueOf(kafkaTuningConfig.getFetchMaxWaitMs()));
       consumerProperties.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
      
       setSSLProperties(consumerProperties);
   	
       ParallelConsumerOptions<String, MeasureInputEvent> options = ParallelConsumerOptions.<String, MeasureInputEvent>builder()
           .ordering(KEY)
           .maxConcurrency(kafkaTuningConfig.getParallelConsumerMaxConcurrency())
           .consumer(new KafkaConsumer<>(consumerProperties))
           .retryDelayProvider(workContainer -> Duration.ofSeconds((long)(10 + Math.pow(Math.E, workContainer.getNumberOfFailedAttempts()))))
           .build();

       ParallelStreamProcessor<String, MeasureInputEvent> eosStreamProcessor = ParallelStreamProcessor.createEosStreamProcessor(options);
       return new ParallelReceiverMode(
           eosStreamProcessor,
           new MeasureProcessorEventsReceiverListener(measureProcessorEventHandler())
           //meterRegistry
       );
   }
```

Parallel consumer subscription to inputs topics:
```
   public void createAndSubscribeInputTopics() {
      // Create and subscribe to input topics
      if (!"".equals(dimensions)) {
         List<String> topicList = new ArrayList<>();
         AnalyticsProperties.TopicConfiguration inputTopicConfig = analyticsProperties.getInputTopic();
         for (String dimension : dimensions.trim().split(",")) {
            String inputTopic = TopicNamesHelper.getInputTopicName(dimension);
            topicList.add(inputTopic);
         }
         if (!topicList.isEmpty() && !topicManager()
            .createTopics(topicList, inputTopicConfig.getNumPartitions(), inputTopicConfig.getReplicationFactor(),
               false, inputTopicConfig.getRetention(), inputTopicConfig.getSegment())) {
            LOG.error("ApplicationConfig.createAndSubscribeInputTopics(): Cannot create input topics [{}]", topicList);
         }
      }
      
      if (kafkaTuningConfig.isParallelConsumer()) {
    	  LOG.info("parallelConsumer is enabled for measure processor events, hence going with parallel consumer instead of regular kafka consumer");
    	  measureProcessorParallelReceiverMode().subscribe(
    		subscriptionManager().getSubscriptionTopics(analyticsProperties.getInputTopic().getName(), MEASURE_CONSUMER_CLIENT_ID));
    	  measureProcessorParallelReceiverMode().execute();
      } else {
    	  subscriptionManager().subscribe(analyticsProperties.getInputTopic().getName(), MEASURE_CONSUMER_CLIENT_ID,
    	      measureProcessorEventListener());
      }

   }
```

Parallel consumer started:
```
public class ParallelReceiverMode implements ReceiverMode {
    private final ParallelStreamProcessor<String, MeasureInputEvent> parallelConsumer;
    private final ReceiveListener receiveListener;
    //private final MeterRegistry registry;

    @Override
    public void execute() {
        parallelConsumer.poll(message -> {
            if (possibleDeserializationError(message)) {
                //logPossibleDeserializationError(message);
                return;
            }
            try {
                getReceiveListener().onReceive(message);
            }
            catch (RuntimeException e) {
                //logMessageFailure(message, e);
            }
        });
    }
```

**Comment by astubbs** [comment]
Hi! Welcome to the project!

At first glance it seems fine. Can you write it as an integration test, extending 'BrokerIntegrationTest'? 

I'm working on a big PR atm - but after I get that merged, I'll take a look. 

And yes it should handle what you describe absolutely no problem.

**Comment by pdeole** [comment]
Thanks @astubbs I was expecting maxConcurrency set to same value as number of consumers in initial design to provide same results however now i am also trying with another configuration of 1 parallel consumer per subscription topic, and would then adjust maxConcurrency to a lower value. e.g. 10 parallel consumer for 10 inputs topics with maxConcurrency of 4 each and see how that works.

**Comment by astubbs** [comment]
Your instincts are correct. Your results do sound odd. I will def look into this by writing a test that scales in that nature, which you'll be able to run yourself to see.

**Comment by astubbs** [comment]
Don't forget it also is important how fast the underlaying consumer can download messages from the brokers. Were they maxed out? PC can't process messages if the consumer underneath is starving it...

**Comment by astubbs** [comment]
You're also talking about max concurrency like it's per partition, but you're using KEY ordering. You'd only need max_concurrency to match num partitions if you were using PARTITION ordering - i.e. one partition per thread. But you're using KEY - so saw you have 1000 unique keys - you'd need MAX_CONCURRENCY set to 1000 to get max possible processing at once.

However, I wouldn't expect PC to be _slower_ with such a config. (aside from the above comment about being starved)

**Comment by pdeole** [comment]
I am not sure why would underlying consumer max out with starving.

Here are some more details:

out of 10 input topics, 7 topics are having heavy traffic. over half a million events an hour being produced onto topics while 3 topics are not that high traffic, sometimes even idle

Out of 7 heavily loaded topics:

3 topics: 4000-5000 unique keys
2 topics: 20 unique keys
2 topics: 600 unique keys

What configuration do you suggest would be best for this kind of traffic?

Secondly, settting max_concurrency to a high number like 1000, wouldn't it cause those many background processor threads to be spawned in the JVM, causing it to halt?

**Comment by astubbs** [comment]
> Secondly, settting max_concurrency to a high number like 1000, wouldn't it cause those many background processor threads to be spawned in the JVM, causing it to halt?

All depends how much memory you're giving the JVM. I got around 1200 before I got an OOM crash, with default JVM settings, on my laptop with the brokers running in docker in the background with pretty good performance. If you want to go high concurrency without using memory - you can look at using the vert.x or reactor modules - they don't use threads to scale up concurrency.


I still intend to make an integration test with your scenario, once I get this PR merged.

**Comment by pdeole** [comment]
Finally, I could get the parallel consumer to scale, with some trial and error with different permutations and combinations.
For 10 input topics, I divided it into heavy duty (6) and low duty (4) topics. 
Created a separate parallel consumer for heavy duty and combined other low duty topic under a single parallel consumer.
Then tuned the maxConcurrency for each parallel consumer as per requirements, so some parallel consumers might be allocated more concurrency than others. With this configuration, I am able to keep the consumer lag to a minimal.

I have one more question: 
since the auto.commit is disabled for parallel consumer and it handles offset commit on each record processed, will it impact performance? 

Or if offsets are committed in batches, then what will be side effect in case the pod (hosting consumer) restarts before offset batch is committed? 
Does it give rise to duplicates when partitions are rebalanced to other consumer pod?

**Comment by astubbs** [comment]
> since the auto.commit is disabled for parallel consumer and it handles offset commit on each record processed, will it impact performance?

No. It doesn't commit every time a message is processed, it only commits every `#timeBetweenCommits`. Even though it tracks the ack for every message, it only actually performs a commit at whatever frequency you choose - default as per Kafka is 5s.

This version of the setting is in the NEXT version. Current version, you set it on the PC object.

https://github.com/confluentinc/parallel-consumer/blob/b2be8dac7b5576135bdb0173c7296bd76e1b7837/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java#L222

> What will be side effect in case the pod (hosting consumer) restarts before offset batch is committed?

Upon clean shutdown, offsets are committed. The PC that gets assigned the partitions to take over, will continue exactly where the shutdown one stopped.

> Does it give rise to duplicates when partitions are rebalanced to other consumer pod?

In the happy path, no. Upon crash - depends how many records were processed between your `#timeBetweenCommits`. So you can reduce the `#timeBetweenCommits`, or use the transactional commit mode which ensures no dupes even on crash (but as per Kafka, side effects will be replayed - i.e. "effectively once" processing).

**Comment by pdeole** [comment]
Talking about clean shutdown, what do i need to do from application? do i need to call close or any other similar method on the PC that will cause a clean shutdown?

Secondly, what about partition rebalance in case a new pod (consumer) is created, so existing partitions from old consumer will go to new one... in this scenario, is there a way to make sure that existing events being processed by existing consumer are processed and offsets are committed before partition gets rebalanced to newly added consumer pod?

**Comment by astubbs** [comment]
>  do i need to call close

yes, call close :)

> what about partition rebalance in case a new pod (consumer) is created, so existing partitions from old consumer will go to new one...

Upon rebalance, upon `#onPartitionRevoked`, a commit is made, so there next PC to get the corresponding `#onPartitionAssigned` loads the commit data correctly - no duplicates.

See here: 
https://github.com/confluentinc/parallel-consumer/blob/7630c96dcf05a60355a394450c08b807085babb6/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java#L335-L361

**Comment by pdeole** [comment]
@astubbs I am using 0.4.0.1 version of library and I presume there are no KEY ordering issues with this version, or please advise if I should upgrade to latest version. The reason I am asking is because I replaced regular consumer with parallel consumer and ours is an analytics application so it is supposed to compute 'measures' from incoming events and with early testing we did with the parallel consumer, the measures were bit skewed from expected. I am yet to run the same test with regular consumer and compare the results yet but just wanted to confirm that I am not using stale version of library.

**Comment by astubbs** [comment]
You should def upgrade to the newest version. 4 is very old now. Generally always stay on at least highest point release. But in this case I suggest you go straight to the newest.

> the measures were bit skewed from expected
Can you elaborate?

**Comment by pdeole** [comment]
the measures were bit skewed from expected
Can you elaborate?

--> So to answer your question, we are building analytics application for
call/contact center, so the agents in call center, for example, are routed
calls from customer, they answer those calls and complete those interaction
with customers. These are the measures like offered calls, answered calls,
completed calls.

So I see a bit more discrepancy between these measures with PC, while the
results with regular consumer are more accurate.

I am planning to move to 0.5.2.3 from 0.4.x version, and i see many API
changes, major one around PollContext.
Is there additional docs around usage of PollContext?
Should I just use PollContext.getSingleConsumerRecord to get the
ConsumerRecord out of it and pass on to my user function listener?

public interface ReceiveListener {
    void onReceive(ConsumerRecord<String, MeasureInputEvent>
consumerRecord);

}

**Comment by pdeole** [comment]
@astubbs I would like to hear from you if there are any plans to include this library as official parallel consumer in Apache kafka and whether there will be official support provided for this. If this library is providing such a good scaling capabilities to kafka based applications then why this is not being included in Apache kafka

**Comment by pdeole** [comment]
closing since got the expected results with different configuration

**Comment by astubbs** [comment]
> @astubbs I would like to hear from you if there are any plans to include this library as official parallel consumer in Apache Kafka

No, there are no plans to do that

> and whether there will be official support provided for this

Yes, that is coming

> If this library is providing such a good scaling capabilities to kafka based applications then why this is not being included in Apache kafka

There is some discussion around this, but it's quite, involved...
