### ISSUE TITLE
Performance: FindCompletedEligibleOffsetsAndRemove method try replacing with cache of incomplete offsets

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#41]
TODO: This entire loop could be possibly redundant, if we instead track low water mark, and incomplete offsets as work is submitted and returned, then we don't need to scan through all the partition collections looking for them.

**Comment by astubbs** [comment]
relates to: #53

**Comment by johnbyrnejb** [comment]
Closing Issue
