### ISSUE TITLE
Kafka Consumer gets stuck after 'controlled shutdown' error in logs

### ISSUE THREAD

**Issue by jatindersthind** [confluentinc/parallel-consumer#416]
I am using ParallelConsumer with Key level parallelism and Periodic consumer sync mode.
It stops processing messages after sometimes, Also the consumer is still shown connected when we describe group.

Error in parallel consumer:
```
io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor - Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: Timeout waiting for commit response PT30S to request ConsumerOffsetCommitter.CommitRequest(id=10322cff-d796-48f3-b0fe-b2111666bd4b, requestedAtMs=1664138997239)
io.confluent.parallelconsumer.internal.InternalRuntimeError: Timeout waiting for commit response PT30S to request ConsumerOffsetCommitter.CommitRequest(id=10322cff-d796-48f3-b0fe-b2111666bd4b, requestedAtMs=1664138997239)
        at io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter.commitAndWait(ConsumerOffsetCommitter.java:159)
        at io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter.commit(ConsumerOffsetCommitter.java:78)
        at io.confluent.parallelconsumer.internal.BrokerPollSystem.retrieveOffsetsAndCommit(BrokerPollSystem.java:313)
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.commitOffsetsThatAreReady(AbstractParallelEoSStreamProcessor.java:1089)
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.commitOffsetsMaybe(AbstractParallelEoSStreamProcessor.java:1012)
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:685)
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:639)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]

```
Looks like this error is just being logged to logger, but consumer close is not happening, hence consumer doesn't pick new messages from kafka.

**Comment by astubbs** [comment]
Hi, welcome to the project!

When does this happen? I'm a bit confused by the order of things here. Are you triggering the close? Could you clarify the order of events?

How often does this happen? Is it reproducible?

What do the logs show when it stops processing?
Can you provide more context in the logs?

Curious, why are you using consumer sync mode?

**Comment by jatindersthind** [comment]
Thanks for your reply.
I haven't triggered the close. This gets triggered automatically. Looks like it is timing out while waiting for commit response from kafka.
We wanted to use syncronous commit mode, to avoid overloading of memory. Is this mode not recommended?
In the logs only this error is shown. Nothing after that. Also as per the code analysis from github for AbstractParallelEoSStreamProcessor, This error is being printed to error stream. After that it tries "doClose())" and then throws the exception. That thrown exception is not getting printed in logs. So I suspect, it is still stuck in doClose().
This error is quite intermittent. Comes after running it for some time (days).
I want to avoid putting DEBUG log on parallel consumer, as it will load logs unnecessarily, Current logging level is INFO

**Comment by astubbs** [comment]
Can you provide the logs around the commit process where it times out?

> We wanted to use syncronous commit mode, to avoid overloading of memory. Is this mode not recommended?

Sync commit is intended to be used where you are sensitive to duplicates. In this mode, no further records will be processed until a positive commit response is received. With Async mode, it doesn't wait - so if there's a crash, you may get higher amount of records replayed. 
Sync mode is slower than async (as it blocks processing).
Sync mode doesn't cause more memory to be used than async - it just blocks processing more records until commit ack is received.

I'll add this info / elaborate to the javadoc for the mode.

Could you elaborate on your memory concerns?

> In the logs only this error is shown. Nothing after that. 

But what about before? 

> Nothing after that. 

Are you saying this the final entry in the logs? The system seems to lock up at this point?

Which version are you using?

Can you include the full context for the logs - particularly the time stamps, line numbers and class info? What config are you using for your logger?

FYI the logback pattern layout used in the tests for the project is:

`<pattern>%d{mm:ss.SSS} %yellow(%X{pcId}) %highlight(%-5level) %yellow([%thread]) %X{offset} %cyan(\(%file:%line\)#%M) %msg%n
`

**Comment by jatindersthind** [comment]
> Could you elaborate on your memory concerns?

We used Synchronous Commit mode, assuming that Asynchronous mode has to keep info for pending offsets in memory. So it might use more memory.

> Which version are you using?

We are using 0.5.2.1 version

> Can you provide the logs around the commit process where it times out?

--------In the previous logs it was just processing messages normally as below---------



[INFO ] 2022-09-26 02:19:52.161 [pc-pool-3-thread-15] com.example.kafka.KafkaClient$KafkaProcessingInterfaceImpl - 'MY-TOPIC' received message, Message = '{"creation_time":1664138992143,"action":"ADD","name":"abc","id":"3290f370-3b31-11ed-98d0-3a942bfb399f-1"}',Url = 'localhost:9092'
[INFO ] 2022-09-26 02:19:52.238 [pc-pool-3-thread-15] com.example.processor.handler.MessageHandler - Message processed time taken: 77 ms



--------Then this error came----------



[ERROR] 2022-09-26 02:20:07.240 [pc-control] io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor - Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: Timeout waiting for commit response PT30S to request ConsumerOffsetCommitter.CommitRequest(id=10322cff-d796-48f3-b0fe-b2111666bd4b, requestedAtMs=1664138997239)
io.confluent.parallelconsumer.internal.InternalRuntimeError: Timeout waiting for commit response PT30S to request ConsumerOffsetCommitter.CommitRequest(id=10322cff-d796-48f3-b0fe-b2111666bd4b, requestedAtMs=1664138997239)        at io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter.commitAndWait(ConsumerOffsetCommitter.java:159) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter.commit(ConsumerOffsetCommitter.java:78) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.BrokerPollSystem.retrieveOffsetsAndCommit(BrokerPollSystem.java:313) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.commitOffsetsThatAreReady(AbstractParallelEoSStreamProcessor.java:1089) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.commitOffsetsMaybe(AbstractParallelEoSStreamProcessor.java:1012) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:685) ~[service-1.0.jar:?]        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:639) ~[service-1.0.jar:?]        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_322]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]


> Are you saying this the final entry in the logs? The system seems to lock up at this point?

Yes this is final entry. After this no log from pc-pool-3-thread-15 thread or pc-control. Looks like it is stuck in doClose method in AbstractParallelEoSStreamProcessor.java

Also, when we describe consumer group on kafka, it still shows this consumer connected, but the lag doesn't reduce, as it is not processing any new messages. Also not releasing the connection (after printing controlled shutdown)

**Comment by astubbs** [comment]
> We used Synchronous Commit mode, assuming that Asynchronous mode has to keep info for pending offsets in memory. So it might use more memory.

Ah ok, no there's no difference in relation to that. They require the same amount of memory.

> We are using 0.5.2.1 version

Please upgrade :) However the upgrade won't affect this issue.

**Comment by astubbs** [comment]
I have a change coming that will help make this situation more clear. However can you see in the logs what happened with the commit from the ConsumerManager? Was there another error?
