### ISSUE TITLE
Question: Poller behavior

### ISSUE THREAD

**Issue by bojanv55** [confluentinc/parallel-consumer#446]
Hi, I cannot find somewhere in documentation how poller part is working. What happens when there are e.g. 5 worker threads, and poller polls 1000 messages per poll? Is there some way of message limiting from kafka?

**Comment by astubbs** [comment]
When the buffers are full /enough/, it pauses the partition and continues calling poll. 
The buffer size is determined by your functions performance, and your max concurrency setting.
