### ISSUE TITLE
Support scheduled message processing (scheduled retry)

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#48]
Having the ability to only process a message at a certain time, say for scheduling sending messages to users.

This could be quite easily achieved by extending the existing retry delay system - give the user function the ability to throw a "retry message X time" exception, the system will then use -this- as the retry delay, instead of the normal retry delay of a few seconds.

The record will then not be given back to a user function, until at least X time has passed.

**Comment by johnbyrnejb** [comment]
Closing Issue
