### ISSUE TITLE
No generic in JStreamParallelStreamProcessor factory method

### ISSUE THREAD

**Issue by acktsap** [confluentinc/parallel-consumer#486]
https://github.com/confluentinc/parallel-consumer/blob/540b0b9a580d4d5d84f50564df5243206b8910f1/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/JStreamParallelStreamProcessor.java#L17-L19

It looks removed in https://github.com/confluentinc/parallel-consumer/pull/223. It is intended?

**Comment by astubbs** [comment]
Hi! You’re the first person to ever ask about this interface :)
Aside from your question, may I know why this interface is your preference?
I’ll take a look soon.

**Comment by astubbs** [comment]
Yes, def. I'll fix it. But I'm also thinking about removing the Stream interfaces.
