### ISSUE TITLE
Feature: Run mode where transition to plain offset committing (no encoded offsets needed)

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#49]
new run mode where encoded offsets are removed.

I.e. the system doesn't take any new messages from Kafka, but keeps running normally, until no offset encoding is required (i.e. low water mark == high water mark) (highest continuous successful block == highest succeeded message (and in this case highest seen message probably)).

This could be useful if the consumption of the topic needs to be handed over to a non-pc consumer, as it removes the need for the special offset encoding, so any consumer will resume from the committed offset and not replay messages already succeeded.

May be a niche use case. But might drop barriers to adoption as there's a road to go back to a normal consumer.

**Comment by johnbyrnejb** [comment]
Closing Issue
