### ISSUE TITLE
Parallel consumer doesn't process any more records due to incorrect management of work

### ISSUE THREAD

**Issue by RaviKalasapur** [confluentinc/parallel-consumer#547]
Parallel Consumer threads pauses polling messages from topic/partitions(s) and hence doesn't invoke user function, due to the "leak" in the counter of non-existent work when partition state changes. (Rebalancing, offline etc).

Confluent library version: 0.5.2.4

Possible (Observed) root cause - 
The problem appears to be stemming from not cleaning up the variable `WorkManager.java#numberRecordsOutForProcessing`, when the partition is revoked (partition epoch changes). The effect is gradual, until the numberOfRecordsOutForProcessing hits the Max value formulated via `ParallelConsumerOptions`.

Due to the above,  the consumer  stops polling/processing messages which causes consumer lag to build up.

Temporary Work Around: Restarting the process.

![PC-Options](https://user-images.githubusercontent.com/30247067/218614997-5d92aeb3-19d7-476a-9c69-da5058f3288a.jpg)

[thread_stack_pc.txt](https://github.com/confluentinc/parallel-consumer/files/10727790/thread_stack_pc.txt)

**Comment by RaviKalasapur** [comment]
My honest attempt to add a test case which fails and a possible fix too. :)

**Comment by bscully-ot** [comment]
cc @rkolesnev
