### ISSUE TITLE
Question: I encountered message loss, how can I check when & where did the offset was commited ?

### ISSUE THREAD

**Issue by whughchen** [confluentinc/parallel-consumer#565]
I am use parallel-consumer 0.5.2.4 **vertx**  dispatch mode.
I force offset %10 ==5 message stuck there for half hour on pursely, kill service and restart it, and i found the consuming offset start from offset %10 ==6, the offset %10 ==5 message was lost.

```java
if(offset!= null && Long.valueOf(offset) % 10 ==5){
    log.info("stick message because offset%10 ==5,  offset="+offset);
    try{
        Thread.sleep(1800 *1000);
    }catch (Exception e){
        log.error(" Thread.sleep",e);
    }
}
```
The message processing is in a Synchronize call, no thread pool. 
When I check the kafka offset, message **offset =1351465**  was already committed while thread is sleeping. 

| Partition  | LogSize  | Consumer Offset  | Lag  |
|  ----  | ----  | ----  | ---- | ---- | 
| 0 | 1,352,076 | 1,351,465 | 611 | 
| 1 | 1,356,801 | 1,356,189 | 612 |
| 2 | 1,354,115 | 1,353,536 | 579 | 

my question is how can I check when & where did the offset=1351465 was committed ?

**Comment by whughchen** [comment]
problem solved

**Comment by astubbs** [comment]
What was your issue / solution? For the crowd..
