### ISSUE TITLE
Are there any plans for .NET parallel consumer implementation?

### ISSUE THREAD

**Issue by bbrandt** [confluentinc/parallel-consumer#572]
We develop our microservices using .NET Core 6 and are looking at using the [Kafka .NET Client by Confluent](https://docs.confluent.io/kafka-clients/dotnet/current/overview.html#ak-dotnet). Are there plans to enable .NET users to use the Parallel Consumers pattern or a way to utilize the current library with .NET microservices?

Thanks!

**Comment by astubbs** [comment]
I'm considering adding an http layer, but it's not high up the list

**Comment by rkolesnev** [comment]
.NET version of the library is not in plans. It is possible to use Parallel Consumer with applications written in other languages through implementing a network call from user function to the service (REST, gRPC etc).
