### ISSUE TITLE
No methor found : groupMetaData | org.apache.kafka.clients.consumer.ConsumerGroupMetadata

### ISSUE THREAD

**Issue by dixitsingla** [confluentinc/parallel-consumer#573]
I am writing a prototype application using parallel consumer and will be consuming an avro record as "GenericRecord", for that I had to use the property `value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer`. for this to work I had to use in build.gradle `implementation 'io.confluent:kafka-avro-serializer:5.3.0'`.  
Due to this `org.apache.kafka.clients` version is changed from 3.3.0 to 5.3.0 and I am getting an error like no method found `groupMetaData | org.apache.kafka.clients.consumer.ConsumerGroupMetadata`. 

Could you please help me with the work around to handle this issue.

**Comment by dixitsingla** [comment]
I tried using `implementation 'io.confluent:kafka-avro-serializer:3.3.0` but with started getting another exception `Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/Jackson/JsonNode`

**Comment by rkolesnev** [comment]
Hi @dixitsingla - it really sounds like dependency issue - can you try to work out appropriate dependencies without Parallel Consumer first to work out kafka-clients + Deserializer ones that you need for your application?
Next step i guess would need to work out dependency exclusions to make sure the transient dependencies match.

If you can post your dependency graphs on working mini app using plain KafkaConsumer and then on Parallel Consumer i can have a look to reproduce and advice.
