### ISSUE TITLE
ByteArray key parallelism is not working as expected

### ISSUE THREAD

**Issue by larinje** [confluentinc/parallel-consumer#579]
When used ByteArray as key in kafka, splitting work by ProcessingOrder.KEY is not working well.
I think because of Lomboks @EqualsAndHashCode, which is not able to infer key type and compare arrays.

I am using ByteArrayDeserializer in my kafka consumer.

![image](https://github.com/confluentinc/parallel-consumer/assets/10121939/3d6c11b3-511e-4455-8e71-c66fd9cffbf3)

```@Test
    void testEqualsKey() {
        assertNotEquals(
                new KeyOrderedKey(new TopicPartition("1", 1), "1".getBytes()),
                new KeyOrderedKey(new TopicPartition("1", 1), "1".getBytes())
        );
        assertEquals(
                new KeyOrderedKey(new TopicPartition("1", 1), "1"),
                new KeyOrderedKey(new TopicPartition("1", 1), "1")
        );
    }

**Comment by johnbyrnejb** [comment]
Hi, we will look into this. 

Thanks
