### ISSUE TITLE
Consumer is not able to poll and process valid messages when a lot of invalid messages occurred

### ISSUE THREAD

**Issue by kapmati** [confluentinc/parallel-consumer#582]
Hi,
I try to understand how parallel-consumer works and I found one case which is not clear to me. I'm not sure if it's an expected behavior or bug.

I have prepared an environment with 1 kafka broker, 1 topic and 3 partitions. There is 10000 events in this topic, with 5 different keys. 1 key is treated by my custom logic as invalid and an exception will be thrown when consumer will try to process message with this key. So there will be around 2000 messages with this invalid key.

ParallelConsumer config with example message handling:
```
var options = ParallelConsumerOptions.<String, String>builder()
        .ordering(KEY) 
        .maxConcurrency(12)
        .consumer(kafkaConsumer)
        .commitMode(PERIODIC_CONSUMER_SYNC)
        .build();

ParallelStreamProcessor<String, String> parallelConsumer = ParallelStreamProcessor.createEosStreamProcessor(options);

parallelConsumer.subscribe(of(inputTopic));

parallelConsumer.poll(context -> {
    if (ERROR_KEY.equals(context.key)) {
       throw new RuntimeException()
   }
   messageHandle.saveToFile(context)
});

```

I've expected that 8000 messages will be processed correctly and 2000 will not. But in this case, only 504 messages were processed correctly and application is not able to process more. Why this happened? I noticed that this behavior occurred only if there is a lot of invalid messages.

If my description is not clear to you, I can prepare and publish a sample project with this case.

**Comment by johnbyrnejb** [comment]
@kapmati can you supply the reproducible code and we will investigate. 

thanks

**Comment by sangreal** [comment]
@kapmati may I know what is the distribution of the invalid message?
Since parallel consumer will retry failed message forever if you don't catch them

**Comment by rkolesnev** [comment]
Closing as seems stale. 
@kapmati please reopen with any new info
