### ISSUE TITLE
0.5.2.6 not published to Maven

### ISSUE THREAD

**Issue by ryan-clancy** [confluentinc/parallel-consumer#605]
It looks like `0.5.2.6` has been added to the [CHANGELOG](https://github.com/confluentinc/parallel-consumer/blob/master/CHANGELOG.adoc), but hasn't been released on GitHub or published to Maven.

I believe I am having the same issue as https://github.com/confluentinc/parallel-consumer/issues/541 which is fixed in that release, can that release please be published?

**Comment by rkolesnev** [comment]
Hi, 

0.5.2.6 is the current development iteration - 0.5.2.6-SNAPSHOT. It is not released as a release version yet.

**Comment by ryan-clancy** [comment]
@rkolesnev - when will that version be released? I think https://github.com/confluentinc/parallel-consumer/pull/548 is an important fix to get released. Alternatively, are there SNAPSHOT versions published anywhere?

**Comment by johnbyrnejb** [comment]
Hi Ryan, 

We are planning an updated release later this week if you are happy to wait for that. If you are in a rush you can build the SNAPSHOT version locally.
