### ISSUE TITLE
Offset map data too large warnings

### ISSUE THREAD

**Issue by botPotyo** [confluentinc/parallel-consumer#647]
We have been trying to implement the parallel consumer in a high event throughput environment and keep getting the following warnings in our logs:
2023-09-22 12:58:04.360  WARN 13 --- [ pc-broker-poll] i.c.p.s.PartitionState                   : Offset map data too large (size: 7844) to fit in metadata payload hard limit of 4096 - cannot include in commit. Warning: messages might be replayed on rebalance. See kafka.coordinator.group.OffsetConfig#DefaultMaxMetadataSize = 4096 and issue #47

At this point consumption stops for a while and then eventually resumes. I understands what is happening and why consumption stops. However, it defeats the purpose of us using the parallel consumer. We need a steady high consumption rate in order to keep up with the producing rate. If consumption stops we fall behind after each stop more an more. At this point we have 500 events per second producing rate and this is our minimum performance test rate. We want this to go up to 2-4000 EPS. We need the consumer to keep up. Which is why we wanted to use the parallel consumer. We tried lowering the commit interval to 1s. Tried switching to PERIODIC_CONSUMER_SYNC. Didn't help. Couldn't really find any other setting in ParallelConsumerOptions that we could play with that would be relevant. 

We are using the parallel consumer through Spring Kafka and we use the following consumer settings:
`
spring:
  kafka:
    consumer:
      properties:
        enable.auto.commit: true
        fetch.max.bytes: 70000000
        fetch.max.wait.ms: 500
        fetch.min.bytes: 50000
        max.partition.fetch.bytes: 50000000
        max.poll.interval.ms: 600000
        max.poll.records: 40000
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
        receive.buffer.bytes: -1
        send.buffer.bytes: -1
`
We also tried with the default values for these properties just to see if that makes a difference. It does not. We even dropped the producing rate to a 100 events per second and only used 2 parallel consumer threads. No help. Still getting the warning and the consumption stops.

Are we trying to use the parallel consumer for something it wasn't design for? Are there any recommended settings we should try? Any help would be appreciated.

**Comment by rkolesnev** [comment]
Hi, 
auto commit should be disabled in the kafka consumer properties - it is managed explicitly by parallel consumer framework.
Can you please try to set the `spring: kafka: consumer: properties: enable.auto.commit: true` to `false`?

How fast is it to process messages? That warning is normally when there are a lot of messages in flight and it cannot encode all of them in the metadata - but my thinking is that in your case it is due to the `auto.commit` setting preventing PC from handling commits properly.
What ordering guarantee are you using - UNORDERED, KEY or PARTITION?

**Comment by rkolesnev** [comment]
Hi,

Basically the warnings mean that there is too many inflight messages to encode in the metadata - it does bitset and runlength encoding simultaneously and picks the smaller encoded result. 
Are you still producing at 500 msg / second? that doesn't sound too high, but i does depend on how slow your processing is and how distributed the keys are - as with key ordering it wont process more than 1 message per unique key at a time.
You can use metrics to see how many messages are inflight, how metadata size is changing over time etc to gather a bit more information and tune it.

How synthetic is the test? 
if the key distribution is different in the test data vs production data - for example low key cardinality (or sending messages in big blocks all with same key) will slow down processing significantly.

For testing purposes only - you can try to switch to UNORDERED processing and see how it behaves - preferably first collecting metrics in KEY ordered and then in UNORDERED modes to compare - that will eliminate key distribution dependency from the picture and give a hint if it copes with load in general or you need more partitions / processing threads / nodes.

**Comment by rkolesnev** [comment]
@botPotyo - any update?

**Comment by botPotyo** [comment]
Ended up integrating the parallel consumer with Spring Kafka and the listener concurrency it provides. Playing around with the number of listener containers and tweaking some other Kafka values seems to address the issue. A single listener container at the level of EPS we need is just not sufficient. But I think for now we are fine. We have options. Thanks for the tips and following up!

**Comment by rkolesnev** [comment]
@botPotyo - would you have an example of the integration with Spring Kafka listener - even if pretty bare-bone?  
I get questions on Spring Kafka integration with PC from time to time and it would be great to add an example to the code-base - that is actually based on real usage :)

**Comment by rkolesnev** [comment]
closing the issue - looks like it is resolved.

**Comment by zhishengzhang** [comment]
How can we reduce the likelihood of encountering “Offset map data too large warnings”? 
For example, by reducing the number of messages pulled or by reducing the number of threads.
