### ISSUE TITLE
Validate Kafka connection using ParallelStreamProcessor.

### ISSUE THREAD

**Issue by mauroa-fd** [confluentinc/parallel-consumer#656]
Hello,

I'm using ParallelStreamProcessor and I want to validate if there is any issue with Kafka.
I've tried to shut down Kafka Connection, but some WARN logs were saying that the broker is not available.

```
Connection to node -1  could not be established. Broker may not be available. 
Bootstrap broker  (id: -1 rack: null) disconnected
```

When I call this method` isClosedOrFailed()` it's returning false, can you explain to me why?
Is it not validating Kafka?

Another situation that I noticed is that the processor state stays as RUNNING...

I intend to have a Spring Boot actuator that can use this method `isClosedOrFailed()` to see Kafka issues.

Any ideas?

Thanks in advance!

**Comment by rkolesnev** [comment]
Hi,
Parallel Consumer depends on Kafka Consumer that is passed to it - connectivity errors like this are treated as retriable / not terminal by the underlying Kafka Consumer - hence Parallel Consumer is not closed / failed.

In general - that is actually a quite complex area - what exactly means Kafka is unavailable / failing - if you look at Spring's Kafka health check implementation - they have went back and forth with different approaches - how to detect reliably that Kafka is down and it is not just a network blip etc. 
Personally - i would advice to implement Kafka health check in your application with criteria that is specific to your usage - and close PC as needed when Kafka is unavailable.
Here is one of relevant discussions on Spring-Kafka side about it and reasons mentioned for generic health indicator not actually available as part of Spring Kafka 
https://github.com/spring-projects/spring-kafka/issues/2573

On the other side - this maybe helpful as basis to give some ideas on how it could be implemented for your application specifically - this is default Spring-Cloud-Stream Kafka health check implementation:
https://github.com/spring-cloud/spring-cloud-stream/blob/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/common/AbstractKafkaBinderHealthIndicator.java
and extended by
https://github.com/spring-cloud/spring-cloud-stream/blob/ba0924acc2933521d0b122b1ec88bea6a35556e4/binders/kafka-binder/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java

**Comment by rkolesnev** [comment]
Closing.

@mauroa-fd - if you have any follow up questions on this topic feel free to re-open.
