### ISSUE TITLE
onOffsetCommitSuccess always cleans partition, even if another work was completed.

### ISSUE THREAD

**Issue by zwendris** [confluentinc/parallel-consumer#664]
Hi, we are seeing some odd behaviour regarding committed offsets and actually completed offsets.

There seems to be a race condition, if an offset/work is completed between the Commiter fetching the offsetToBeCommitted and marking the offset as succesfully committed:

https://github.com/confluentinc/parallel-consumer/blob/0c9b7da5ee2c02b1f90b3aa56a309f568fb906fb/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractOffsetCommitter.java#L32-L43

The PartitonState is changed to NON-dirty when onOffsetCommitSuccess is called, but if a piece of work was completed in the meantime it should stay dirty to ensure the new offset will be committed.

Test might look something like:
```

        final long completedOffset = 1L;
        final long incompleteOffset = 2L;

        final HighestOffsetAndIncompletes offsetData = new HighestOffsetAndIncompletes(Optional.of(incompleteOffset), new TreeSet<>(Collections.singleton(incompleteOffset)));
        PartitionState<String, String> state = new PartitionState<>(0, mu.getModule(), tp, offsetData);

        // fetch committable/completed offset
        OffsetAndMetadata offsetAndMetadata = state.createOffsetAndMetadata();

        assertThat(offsetAndMetadata).getOffset().isEqualTo(completedOffset+1);

        // mark incomplete work as complete
        state.onSuccess(incompleteOffset);
        assertThat(state).isDirty();

        //mark fetched offset as committed
        state.onOffsetCommitSuccess(offsetAndMetadata);

        // partition should stay dirty, since the newly completed work could be committed now.
        assertThat(state).isDirty();
```

As long as there are no new messages on this partition there will always be consumer lag > 0, which is wrong and messes with tools like burrow, that think the consumer stopped working.

**Comment by rkolesnev** [comment]
Hmm - i see the issue, the simple fix in the linked PR should do it i think.
