### ISSUE TITLE
parallel-consumer-example-core failing

### ISSUE THREAD

**Issue by tsuz** [confluentinc/parallel-consumer#678]
When running `mvn package` in `parallel-consumer-examples/parallel-consumer-example-core`, I get this error.

```
[ERROR] Failed to execute goal on project parallel-consumer-example-core: Could not resolve dependencies for project io.confluent.parallelconsumer:parallel-consumer-example-core:jar:0.5.2.8-SNAPSHOT: The following artifacts could not be resolved: io.confluent.parallelconsumer:parallel-consumer-core:jar:0.5.2.8-SNAPSHOT (absent), io.confluent.parallelconsumer:parallel-consumer-core:jar:tests:0.5.2.8-SNAPSHOT (absent): io.confluent.parallelconsumer:parallel-consumer-core:jar:0.5.2.8-SNAPSHOT was not found in https://packages.confluent.io/maven/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of confluent has elapsed or updates are forced -> [Help 1]
```

because 0.5.2.8-snapshot is not in the remote repository.

![Screenshot 2023-12-28 at 11 40 03](https://github.com/confluentinc/parallel-consumer/assets/6927131/b4475b7f-0536-4119-828b-d062a3d37b32)

The version should be set to `<version>0.5.2.7</version>`

**Comment by tsuz** [comment]
We can fix the example but how can we get [0.5.2.8][1] onto the MVN repository? 

[1]: https://github.com/confluentinc/parallel-consumer/blob/master/CHANGELOG.adoc#0-5-2-8

**Comment by rkolesnev** [comment]
We should be releasing 0.5.2.8 soon. But generally to do the Examples build on the snapshot version / master branch - you would need to do `mvn install ` on the main project first.
Snapshot versions are not released to Maven and so any sub-project that depends on core libraries would need those built / installed into local maven repo first.

**Comment by tsuz** [comment]
@rkolesnev 

Thanks for confirming - that's partly due to lack of my Java expertise. Understood the situation now.
