### ISSUE TITLE
Release 0.5.2.8 to Maven

### ISSUE THREAD

**Issue by C0mbatwombat** [confluentinc/parallel-consumer#679]
Hi, would it be possible to release 0.5.2.8?
Thanks

**Comment by pleszczy** [comment]
The crucial fix addressed in [PR #665](https://github.com/confluentinc/parallel-consumer/pull/665) was merged on November 20th. Releasing version 0.5.2.8 with this fix would be immensely beneficial for our operations. Your efforts are greatly appreciated, and we look forward to the update. Thank you for your continuous work on this project!

**Comment by rkolesnev** [comment]
released
https://repo1.maven.org/maven2/io/confluent/parallelconsumer/parallel-consumer-core/0.5.2.8/

**Comment by C0mbatwombat** [comment]
Thanks!
