### ISSUE TITLE
ReactorProcessor does not take PCRetriableException into consideration 

### ISSUE THREAD

**Issue by brp-jakob** [confluentinc/parallel-consumer#733]
Im using ReactorProcessor. On some failures I return an error with PCRetriableException but there is still an error log. See: 

https://github.com/confluentinc/parallel-consumer/blob/d337fe5dc1f1669293d2a29f12610ba2d6fbaab4/parallel-consumer-reactor/src/main/java/io/confluent/parallelconsumer/reactor/ReactorProcessor.java#L116

I would suspect something similiar like this is missing: 
https://github.com/confluentinc/parallel-consumer/blob/d337fe5dc1f1669293d2a29f12610ba2d6fbaab4/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java#L1282

Or is it something I have misunderstood?

**Comment by rkolesnev** [comment]
Hi @brp-jakob,

You are right - that check is missing from Reactor Processor.
Would you mind doing a PR to add it?

**Comment by brp-jakob** [comment]
Sure. But I'd like some guide on what branch to create it against. I found 0.5.2.x-dev, is that correct?

**Comment by rkolesnev** [comment]
Normal flow would be to:

- fork the repository  
- create a feature branch off 'master' branch in the fork 
- implement the changes on that feature branch in the fork
- raise a PR back to confluentinc/master from your fork feature branch

More detailed guides on this workflow
https://reflectoring.io/github-fork-and-pull/
https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by rkolesnev** [comment]
Merged. Closing the issue.
