### ISSUE TITLE
Can all subscribers share one user-function threadpool?

### ISSUE THREAD

**Issue by dumontxiong** [confluentinc/parallel-consumer#763]
Hi team,
I found per ParallelStreamProcessor own :
1. one Heartbeat-thread
2. one Pc-broker-poll thread
3. Pc-controll thread
4. Pc-pool-1-thread-XXX (threadpoll)
If my service have multiple subscribers that mean we'll have multiple ParallelStreamProcessors, multiple user-function threadpools.
Then my service will have lots of active threads.
Is there any way those subscribers(ParallelStreamProcessors) could share user-function threadpool?

BRs

**Comment by rkolesnev** [comment]
Hi,
No, not really - it maybe technically possible - but Parallel Consumer code is not written to handle such scenario. For example on shutdown of Parallel Consumer instance - it will call shutdown on the worker thread pool executor.

I am not sure what do you mean by having multiple subscribers in your service - could you elaborate?
Single Parallel Consumer instance can be subscribed to multiple partitions within multiple topics.

What is "lots" of active threads? It is designed to work with large thread pool for high concurrent blocking / slow workloads - so having hundreds to thousands of threads is normal for this.
But if that is prohibitive - there are Reactor and Vert.x based implementations as well.

**Comment by rkolesnev** [comment]
Closing - reopen for any followup questions.
