### ISSUE TITLE
Support Kafka-clients:3.7.0

### ISSUE THREAD

**Issue by dumontxiong** [confluentinc/parallel-consumer#775]
Hi team
io.confluent.parallelconsumer:parallel-consumer-core:0.2.5.8 not support Kafka-clients:3.7.0
Cause AbstractParallelEoSStreamProcessor.checkAutoCommitIsDisabled row 265 :
Field coordinatorField = consumer.getClass().getDeclaredField("coordinator") will throw NoSuchFieldException.
The RCA is KafkaConsumer（3.6.0） is very different with  KafkaConsumer（3.7.0）,KafkaConsumer（3.7.0） doesn't contain coordinator and other fields
BRs,
Dumont

**Comment by nscuro** [comment]
Duplicate of #721, fixed in #762.
