### ISSUE TITLE
Release of 0.5.2.9

### ISSUE THREAD

**Issue by bernardmo** [confluentinc/parallel-consumer#790]
Greetings and thx for the great lib :slightly_smiling_face: 

I was wondering when will the v0.5.2.9 be available on maven central? It includes the fix for #775 and kc:3.7 is default for spring boot 3.3+

**Comment by rkolesnev** [comment]
We are preparing release right now - just ironing out some kinks in the release pipeline after CI migration. 
Should be out this week.
