### ISSUE TITLE
PC keeps retrying in loop on InvalidPidMappingException: The producer attempted to use a producer id which is not currently assigned to its transactional id

### ISSUE THREAD

**Issue by mikhelef** [confluentinc/parallel-consumer#830]
Hi, 

Seems like Parallel Consumer is not handling InvalidPidMappingException correctly in transactional mode with UNORDERED processing. When this exception occurs, Parallel Consumer enters a retry loop, repeatedly attempting to process the same record and encountering the same exception each time. This results in the consumer becoming stuck, unable to make progress.
The TransactionalId is unique per producer, I use UUID when defining it.
Also, I am using Poll&Produce method, I don't think I am able to handle the exception in my code.

## Expected Behavior

When encountering an InvalidPidMappingException, maybe Parallel Consumer should close the producer that is causing this error and create a new producer instance.

## Configuration: 

Parallel consumer version : `0.5.2.8`

```java
//Parallel Consumer
    ParallelConsumerOptions<String, String> options = 
ParallelConsumerOptions.<String, String>builder()
                .maxConcurrency(16)
                .messageBufferSize(50)
                .batchSize(1)
                .ordering(ProcessingOrder.UNORDERED)
                .commitMode(CommitMode.PERIODIC_TRANSACTIONAL_PRODUCER)
                .build();

//Producer transactional id
transactional.id= TRANSACTIONAL_ID_PREFIX+ UUID.randomUUID();
```

Thank you for your help.

**Comment by mikhelef** [comment]
Hi,

**Comment by mikhelef** [comment]
Hi,

Unfortunately, I am unable to reproduce the bug. It occurred after two days of inactivity from the producer, which is less than the 7-day transactional.id.expiration.ms setting. 

The issue might be due to a broker failure, but I cannot be certain. In any case, I believe that parallel consumer should create a new transaction with a new instance of the producer and not retry the same transaction repeatedly, as this will always fail.

**Comment by mikhelef** [comment]
Hello,

Any update on this please ? 

Thanks in advance.
Massi

**Comment by rkolesnev** [comment]
Hi @mikhelef - not really, I am still trying to work out what happened / could have happened to cause the error and how better to react to it.
Would treating that error as a critical error work? 
I am not really sure if we can safely restart transaction without losing work done in the current transaction - so it may be better to close Parallel Consumer on error and let application handle rebalance / restart of it.

But before i dig deeper there - can you provide logs from the error occurrence?
How was it retried - was the error thrown up into the Parallel Consumer and message was retried by retry logic in Parallel Consumer or the retries were internal to Producer?

**Comment by mikhelef** [comment]
Hi @rkolesnev,

Thank you for your response.

Yes, I will implement the change shortly.

Regards,
Massi
