### ISSUE TITLE
Can metaPayloadLength reach to OffsetMapCodecManager.DefaultMaxMetadataSize (4KB)?

### ISSUE THREAD

**Issue by dumontxiong** [confluentinc/parallel-consumer#831]
Hi team
0.5.3.1
PartitionState.java 275

` private boolean updateBlockFromEncodingResult(String offsetMapPayload) {
        int metaPayloadLength = offsetMapPayload.length();
        boolean mustStrip = false;
        if (metaPayloadLength > OffsetMapCodecManager.DefaultMaxMetadataSize) {
            mustStrip = true;
            this.setAllowedMoreRecords(false);
            log.warn("Offset map data too large (size: {}) to fit in metadata payload hard limit of {} - cannot include in commit. Warning: messages might be replayed on rebalance. See kafka.coordinator.group.OffsetConfig#DefaultMaxMetadataSize = {} and issue #47.", new Object[]{metaPayloadLength, OffsetMapCodecManager.DefaultMaxMetadataSize, OffsetMapCodecManager.DefaultMaxMetadataSize});
        } else if ((double)metaPayloadLength > this.getPressureThresholdValue()) {
            this.setAllowedMoreRecords(false);
            log.warn("Payload size {} higher than threshold {}, but still lower than max {}. Will write payload, but will not allow further messages, in order to allow the offset data to shrink (via succeeding messages).", new Object[]{metaPayloadLength, this.getPressureThresholdValue(), OffsetMapCodecManager.DefaultMaxMetadataSize});
        } `

for messages keep failed scenario,I found when metaPayloadLength reached to 75% of limit, no more records would be took for processing, framework would stop encoding(cause there's no succeed messages), so I think metaPayloadLength wouldn't getting larger.
So I think  metaPayloadLength would never greater than OffsetMapCodecManager.DefaultMaxMetadataSize
It's  " if (metaPayloadLength > OffsetMapCodecManager.DefaultMaxMetadataSize) " necessary here ?

BRs,
Dumont

**Comment by rkolesnev** [comment]
Hi @dumontxiong - it is a defensive check - as payload is encoded on commit - encoded size can jump from < `pressureThresholdValue` to > `DefaultMaxMetadataSize` between two commits - if we try to send payload over the maximum - the commit will fail - so we do have to trim the encoded data in that case. 

The second check blocks new messages from being processed until pending messages drain sufficiently to reduce required encoded payload size to reduce that likelihood.

**Comment by dumontxiong** [comment]
@rkolesnev thanks!
