### ISSUE TITLE
[OOM]Offset map reached to 75% pc-broker-poll thread would keep polling records lead to OOM

### ISSUE THREAD

**Issue by dumontxiong** [confluentinc/parallel-consumer#832]
Hi team,
from pc_metadata_space_used metric we can see after 17:38 framework stop encoding
<img width="1083" alt="Screenshot 2024-09-10 at 17 09 42" src="https://github.com/user-attachments/assets/56555ae5-c415-459b-9ab5-46af67bbb260">
 and we can see the log:
io.confluent.parallelconsumer.state.PartitionState couldBeTakenAsWork 649 PartitionState.java - Not allowed more records for the partition (XXX) as set from previous encode run (blocked), that this record (571268) belongs to, due to offset encoding back pressure, is within the encoded payload already (offset lower than highest succeeded, not in flight (true), continuing on to next container in shardEntry.

But pc-broker-poll poll records all the time( from the below kafka_consumer_fetch_manager_bytes_consumed_rate metrics) :

<img width="1169" alt="Screenshot 2024-09-11 at 10 38 21" src="https://github.com/user-attachments/assets/e18b1dc9-d9f9-46f8-9d13-7385ee65a08d">

and from pc_waiting_records metrics we can see waiting records keep increasing.

<img width="1337" alt="Screenshot 2024-09-11 at 13 46 37" src="https://github.com/user-attachments/assets/a930409c-e77a-4cf0-8b28-f961188e07b6">

**And service threw OOM at the end**

And I have two concerns now:
1. pc_waiting_records metric values are negative, Is that normal?
2. when offset map reached to 75% and not allowed more records been processed, would pc-broker-poll thread keep polling records bring any memory issues?

BRs,
Dumont

**Comment by dumontxiong** [comment]
@rkolesnev 

back pressure logic is worked. It is indeed pausing the processing of records now, but the pausing of polling is not worked. It keeps polling records and causes OOM.

**configuration**：
ordering=KEY
maxConcurrency=14
commitmode=PERIODIC_CONSUMER_SYNC
No other parameters are explicitly specified.

scenario:
My test scenario is a scenario where 50% of records fail, and if it fails, it will keep retrying until it succeeds (in fact, it will never succeed, just keep retrying). At this time, the CPU is almost 100%.
So it is high load,high number of retries.

BRs,
Dumont

**Comment by rkolesnev** [comment]
@dumontxiong - the backpressure logic is exactly the logic that controls the polling for records - so there must be an issue in there - potentially caused by something being off with the calculation of retries (given that your scenario seems to be with high number or retries). It is separate from accepting work into worker threads based on metadata size usage.
Can you provide a reproduction code for this? either as a small application or integration test?

**Comment by dumontxiong** [comment]
@rkolesnev 
Here's  two. Scheduled tasks,
one is publish records to topic1 with random key(half with THROW_EXCEPTION_FLAG header), 
one is publish records to topic2 with key 0 - 999 (half with THROW_EXCEPTION_FLAG header), 

`@Scheduled(fixedRate = 2, timeUnit = TimeUnit.MINUTES)
	public void publishEventsNoKey() {
		for (int i = 0; i < 1000; i++) {
			kafkaEvent.setHeader(THROW_EXCEPTION_FLAG, i%2);
			publisher.publish(kafkaEvent);
		}
	}

	@Scheduled(fixedRate = 2, timeUnit = TimeUnit.MINUTES)
	public void publishEventsOneThousandKey() {
		for (int i = 0; i < 1000; i++) {
                      kafkaEvent.setKey(i);
                      kafkaEvent.setHeader(THROW_EXCEPTION_FLAG, i%2);
		     publisher.publish(kafkaEvent);
		}
	}`

Here's  two. subscriber , one is subscribed to topic1 the other is  subscribed to  topic2,and both of them concurrency = 14

`
           ParallelConsumerOptions.ParallelConsumerOptionsBuilder<KafkaEventKey, T> builder = 
            ParallelConsumerOptions.builder().ordering(ProcessingOrder.KEY).maxConcurrency(14).consumer(this.consumer);
            ParallelConsumerOptions options = builder.build();
            this.parallelStreamProcessor = ParallelStreamProcessor.createEosStreamProcessor(options);
           this.parallelStreamProcessor.subscribe("topic1);
            this.parallelStreamProcessor.poll((context) -> {
                try {
      Thread.sleep(100);
    } catch (InterruptedException e) {
     //
    }
    if (kafkaevent.getHeader(THROW_EXCEPTION_FLAG) != null && event.getMeta(THROW_EXCEPTION_FLAG, Integer.class) == 0){
      throw new RuntimeException("THROW_EXCEPTION_FLAG_HAPPENED");
    }
            });
`

`
           ParallelConsumerOptions.ParallelConsumerOptionsBuilder<KafkaEventKey, T> builder = 
            ParallelConsumerOptions.builder().ordering(ProcessingOrder.KEY).maxConcurrency(14).consumer(this.consumer);
            ParallelConsumerOptions options = builder.build();
            this.parallelStreamProcessor = ParallelStreamProcessor.createEosStreamProcessor(options);
           this.parallelStreamProcessor.subscribe("topic2);
            this.parallelStreamProcessor.poll((context) -> {
                try {
      Thread.sleep(100);
    } catch (InterruptedException e) {
     //
    }
    if (kafkaevent.getHeader(THROW_EXCEPTION_FLAG) != null && event.getMeta(THROW_EXCEPTION_FLAG, Integer.class) == 0){
      throw new RuntimeException("THROW_EXCEPTION_FLAG_HAPPENED");
    }
            });
`

**Comment by rkolesnev** [comment]
Thank you for the repro code - will run and see if i can reproduce / see where the issue occurs.

**Comment by rkolesnev** [comment]
Is the CommitMode set to PERIODIC_CONSUMER_SYNC in the example code above - or its left as default (PERIODIC_CONSUMER_ASYNCHRONOUS)?
You mentioned above that you are using PERIODIC_CONSUMER_SYNC in your tests - but in the example code it doesnt seem to be specified...

**Comment by rkolesnev** [comment]
In addition - those events that have the THROW_EXCEPTION_FLAG - are they set to throw exception always? i.e. retried indefinitely and always fail due to throwing exception or they only throw exception first time - but are not failing on retry?
Its not 100% clear what this block does as those objects are not in the code sample provided:
```
(kafkaevent.getHeader(THROW_EXCEPTION_FLAG) != null && event.getMeta(THROW_EXCEPTION_FLAG, Integer.class) == 0)
```

**Comment by rkolesnev** [comment]
recreated issue. 
it is due to #817.

**Comment by dumontxiong** [comment]
> Is the CommitMode set to PERIODIC_CONSUMER_SYNC in the example code above - or its left as default (PERIODIC_CONSUMER_ASYNCHRONOUS)? You mentioned above that you are using PERIODIC_CONSUMER_SYNC in your tests - but in the example code it doesnt seem to be specified...

sorry for miss this one 
```
.commitMode(PERIODIC_CONSUMER_SYNC);
```

**Comment by dumontxiong** [comment]
> In addition - those events that have the THROW_EXCEPTION_FLAG - are they set to throw exception always? i.e. retried indefinitely and always fail due to throwing exception or they only throw exception first time - but are not failing on retry? Its not 100% clear what this block does as those objects are not in the code sample provided:
> 
> ```
> (kafkaevent.getHeader(THROW_EXCEPTION_FLAG) != null && event.getMeta(THROW_EXCEPTION_FLAG, Integer.class) == 0)
> ```

 throw exception would always fail
