### ISSUE TITLE
CommitMode: Individual message commit mode?

### ISSUE THREAD

**Issue by shreeramkulkarni** [confluentinc/parallel-consumer#842]
Hi Folks,

I am recently got to know about this cool library and have a query on commit mode (it might sound a little silly).

I am aware that commit modes are all periodic, which means that there always a chance of duplicate message processing. 
Was there any consideration given to providing users with the option to commit offsets after processing individual messages? I assume this option was not provided to avoid I/O overhead??

Committing offset individually could get us closer to exactly once semantics at the cost of network.
Also, I am looking if there is a way/hook to extend this functionality ourselves.

Thanks!

**Comment by shreeramkulkarni** [comment]
Since this is not an issue, moving it to Q&A forum.

**Comment by rkolesnev** [comment]
relevant discussion - https://github.com/confluentinc/parallel-consumer/discussions/743
