### ISSUE TITLE
Close error: KafkaConsumer is not safe for multi-threaded access

### ISSUE THREAD

**Issue by rakrak98** [confluentinc/parallel-consumer#86]
Hello,
I am trying to run the parallel-consumer-core example but I am having issues get it to run. I am currently running a raw kafka consumer client, and I integrated the parallel consumer code into the project. However, I am getting the following error. Please let me know if you have any ideas why. Thanks!

`ParallelConsumerOptions options = ParallelConsumerOptions.<K,V>builder()
                    //.ordering(KEY)
                    .maxConcurrency(2)
                    .consumer(consumer)
                    .build();`

`ParallelStreamProcessor<K,V> parallelKafkaConsumer1 =
                    ParallelStreamProcessor.createEosStreamProcessor(options);`

 `parallelKafkaConsumer1.subscribe(topic);`
`parallelKafkaConsumer1.poll(record -> System.out.println(record.value()));`

`Waitiing for new messages
ERROR	2021-03-15 19:31:35,988	3	io.confluent.parallelconsumer.BrokerPollSystem	[broker-poll]	Unknown error
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2244)
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2228)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1180)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1176)
	at io.confluent.parallelconsumer.ConsumerManager.poll(ConsumerManager.java:41)
	at io.confluent.parallelconsumer.BrokerPollSystem.pollBrokerForRecords(BrokerPollSystem.java:185)
	at io.confluent.parallelconsumer.BrokerPollSystem.controlLoop(BrokerPollSystem.java:105)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code -1`

**Comment by rakrak98** [comment]
Update on this issue: Initially, I placed the above code in a try-catch block, as follows
`try{
            ParallelConsumerOptions options = ParallelConsumerOptions.<K,V>builder()
                    //.ordering(KEY)
                    .maxConcurrency(2)
                    .consumer(consumer)
                    .build();
            parallelKafkaConsumer =
                    ParallelStreamProcessor.createEosStreamProcessor(options);
            parallelKafkaConsumer.subscribe(topic);
            parallelKafkaConsumer.poll(record -> System.out.println(record.value()));
}catch (Exception e) {
            e.printStackTrace();
        } finally {
            parallelKafkaConsumer.close();
            consumer.close();
        }`
After some bebugging, the part that was causing this issue was within the finally block, where I closed the parallel consumer and raw kafka consumer. Commenting both of those close methods out resolved this particular issue, but raised a new issue, #87

**Comment by astubbs** [comment]
Is the consumer you created only used with PC?

If you just remove the consumer.close does it still fail? PC closes it's underlaying consumer for you.

**Comment by rakrak98** [comment]
Ended up partially resovling this error with ticket #87. However, I do have a response to your comment. Commenting out ONLY consumer.close(), and leaving in parallelKafkaConsumer.close() ends up closing the consumer and does not even allow the consumer to join the Kafka Cluster. In other words, I see no logs from the group-coordinator in the cluster. However, if I were to also comment out parallelKafkaConsumer.close(), the consumer then ends up joining the cluster/consumer group.

**Comment by astubbs** [comment]
That’s because you’re calling close after calling poll. Poll does not block your thread.
By removing the close commands, your thread exits, but PC continues running. 

I’ll check the Java doc to see to make that more clear. Give that a shot :)

**Comment by rakrak98** [comment]
> That’s because you’re calling close after calling poll. Poll does not block your thread.
> By removing the close commands, your thread exits, but PC continues running.
> 
> I’ll check the Java doc to see to make that more clear. :)

Thanks for the help! btw, I finally figured out the solution from the ticket that you closed the other day. The problem was that I was initializing the KafkaConsumer and ParallelStreamProcessor objects as class variables, but I did not declare them as static.
