### ISSUE TITLE
VertxParallelStreamProcessor create a lot of threads

### ISSUE THREAD

**Issue by radoslawtwardy** [confluentinc/parallel-consumer#97]
Referring to the discussion in https://github.com/confluentinc/parallel-consumer/pull/94 I create this issue. I have some code (I use released 0.3.0.1 version):

    package parallel.consumer.vertx.test;
    
    import io.confluent.parallelconsumer.ParallelConsumerOptions;
    import io.confluent.parallelconsumer.vertx.VertxParallelStreamProcessor;
    import org.apache.kafka.clients.consumer.KafkaConsumer;
    import org.apache.kafka.clients.producer.KafkaProducer;
    import org.apache.kafka.clients.producer.Producer;
    import org.apache.kafka.clients.producer.ProducerRecord;
    import org.apache.kafka.common.serialization.StringDeserializer;
    import org.apache.kafka.common.serialization.StringSerializer;
    
    import java.util.Collections;
    import java.util.Properties;
    import java.util.UUID;
    
    import static io.confluent.parallelconsumer.ParallelConsumerOptions.ProcessingOrder.UNORDERED;
    
    public class App {
        public static void main(String[] args) {
    
            String bootstrapServer = "localhost:9092";
    
            String topicName = "parallel-consumer-vertx-test-topic";
    
            int maxConcurrency = 1000;
    
            Properties consumerProps = new Properties();
            consumerProps.put("bootstrap.servers", bootstrapServer);
            consumerProps.put("group.id", "parallel-consumer-vertx-test");
            consumerProps.put("key.deserializer", StringDeserializer.class.getName());
            consumerProps.put("value.deserializer", StringDeserializer.class.getName());
            consumerProps.put("auto.offset.reset", "earliest");
            consumerProps.put("enable.auto.commit", "false");
    
            KafkaConsumer<String, String> consumer = new KafkaConsumer<>(consumerProps);
    
            Properties producerProps = new Properties();
            producerProps.put("bootstrap.servers", bootstrapServer);
            producerProps.put("key.serializer", StringSerializer.class.getName());
            producerProps.put("value.serializer", StringSerializer.class.getName());
    
            Producer<String, String> producer = new KafkaProducer<>(producerProps);
    
            ParallelConsumerOptions<String, String> options = ParallelConsumerOptions.<String, String>builder()
                    .ordering(UNORDERED)
                    .maxConcurrency(maxConcurrency)
                    .consumer(consumer)
                    .build();
    
            VertxParallelStreamProcessor<String, String> vertxProcessor = VertxParallelStreamProcessor.createEosStreamProcessor(consumer, null, options);
            vertxProcessor.subscribe(Collections.singletonList(topicName));
    
            vertxProcessor.vertxHttpWebClient(
                    (client, record) ->
                            client
                               .postAbs("https://extendsclass.com/mock/rest/ed3ef0d0f594bf944629b6d5bce49ec3/parallelconsumervertxtest")
                               .send(),
                    resp -> resp.onSuccess(r -> System.out.println(r.statusCode() + " - " + r.body().toString()))
            );
    
            for(int i = 0; i < maxConcurrency * 2; i++) {
                String id = UUID.randomUUID().toString();
                ProducerRecord<String, String> record = new ProducerRecord<>(topicName, id, "TEST " + i);
                producer.send(record);
            }
        }
    }

If i run this main i see two alarming issues:
- Max concurrency is set to 1000, but I see that vertx crate only few http request at same time
- I se 1000 threads which doasn't do anything special

  "pool-1-thread-1@3577" prio=5 tid=0x18 nid=NA waiting
    java.lang.Thread.State: WAITING
	    at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	    at java.lang.Thread.run(Thread.java:830)

I would expect that i has reasonable number of threads and parallelism close to maxConcurrency (because number of http requests should be limited only by number of sockets).
I hope that my problem which I previously described is clear.

**Comment by astubbs** [comment]
Thanks! Yes that’s doesn’t sound right. I have a feeling after I changed the way the options work, I didn’t update the vertx module. So need to add some basic assumption tests and tweak something. Shouldn’t be a big problem. I’ll look at it today.

**Comment by astubbs** [comment]
Thanks very much for uncovering this! I've added tests which capture the issue, and have fixed the problem. I'm just polishing up the tests now and checking some other things.

**Comment by astubbs** [comment]
Okay if you want to pull down that pull request, and install it - you should be able to run against that snapshot version and see if your issue is fixed. I think I've resolved it. Thank you again! :)

**Comment by radoslawtwardy** [comment]
I've tried this pull request and everything works fine for me. Thank you!

**Comment by astubbs** [comment]
Great! I’m going to do a release early this week that’ll release this fix and a few other light ones. Thanks for the help! And do let me
Know how it works out for you, any other additions or improvements you might like, and have a vote on existing feature plans! :)
