### ISSUE TITLE
Remove non vertx operations from vertx implementation

### ISSUE THREAD

**Issue by astubbs** [confluentinc/parallel-consumer#99]
Will probably need to refactor out a common parent to do it nicely. Shouldn't be too hard though. 

People might instantiate a vertx implementation but mistaking luck use the vanilla methods, where the thread pool size is only one. 

I can't think right now of a good reason to keep them both available in the vertx implementation.

**Comment by astubbs** [comment]
@radoslawtwardy any thoughts?

**Comment by radoslawtwardy** [comment]
I think removing methods such as poll, pollAndProduce etc. from vertx implementation is good idea.
